# Dev environment â€“ use in Dokploy with branch e.g. develop/dev
# In Dokploy: set Compose path to "docker-compose-dev.yaml"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kzen-node-dev
    ports:
      - "8009:8008"
    restart: unless-stopped
    env_file:
      - .env
